### ISSUE TITLE
Style Tracker

### ISSUE THREAD

**Issue by jamesrswift** [JamesxX/ionio-illustrate#1]
This issue will track the progress towards allowing styling on the graph components using Cetz style dictionaries.

Tracking chart:

- [x] Styling for axes
- [x] Styling for all peaks
- [x] Styling for specific peaks
- [x] Styling for peak annotations
- [x] Styling for mass callipers
