### ISSUE TITLE
`dual-reflection` display mode

### ISSUE THREAD

**Issue by jamesrswift** [JamesxX/ionio-illustrate#3]
Tracking issue for dual display mode. Current objectives are:
- [x] Handle data input
- [x] Handle how axes are calculated
- [x] Handle `plot-extra` functions
    - [x] Pass additional option,  maybe automatically somehow? Store state on #ms?
    - [x] Adjust labels to account for vertical space on reflected pane.
    - [x] Adjust callipers
